name: Combined workflow
on: [push, pull_request]
env:
  dotnet-version: '8.0.x'
  runs-on: unbunty-latest
jobs:
  build:
    runs-on: ${{unbunty-latest}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/dotnet@v4
        with: 
          dotnet-version: ${{env.dotnet-version}}
      - name: Build project
        run: dotnet build Lab/Lab.csproj

  test:
    needs: build
    runs-on: ${{unbunty-latest}}
    strategy:
      matrix:
        configuration:  [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/dotnet@v4
        with: 
          dotnet-version: ${{env.dotnet-version}}
      - name: Run tests
        run: dotnet test Lab/Lab.csproj --configuration ${{matrix.configuration}}

  analyze:
    needs: build
    runs-on: ${{unbunty-latest}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run code analysis
        run: dotnet tool install -g dotnet-format && dotnet format Lab/Lab.csproj
