name: Publishing artifacts with multiple configurations
on: [pull_request]

jobs:
  build:
    runs-on: ubunty-latest
    strategy:
      matrix: 
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build project
        run: dotnet build Lab/Lab.csproj --configuration ${{matrix.configuration}}
      - name: Upload artifacts
        uses: actions/upload-arthifact@v4
        with:
          path: artifacts/
      
  test:
    runs-on: ubunty-latest
    strategy:
      matrix: 
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run tests
        run: dotnet test Lab/Lab.csproj --configuration ${{matrix.configuration}}
